git:
  pagers:
    - colorArg: always
      pager: delta --features="catppuccin-mocha" 
      useConfig: false
    - colorArg: always
      pager: delta --features="catppuccin-mocha" -s
      useConfig: false


gui:
  sidePanelWidth: 0.3

  expandFocusedSidePanel: true
  expandedSidePanelWeight: 3

  showFileTree: false
  showNumstatInFilesView: true
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false
  showPanelJumps: false

  promptToReturnFromSubprocess: false

  theme:
    activeBorderColor:
      - '#f2cdcd'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#f2cdcd'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
  authorColors:
    '*': '#b4befe'
